services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  java-app:
    image: java_web_server:0.0.1
    restart: always
    ports:
      - 8043:8080
    environment:
      CONN: jdbc:postgresql://postgres:5432/postgres?user=postgres&password=${DB_PASSWORD}
    depends_on: 
     - postgres

networks:
  common-nw: